cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

plyart_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import SendFormTelegram

urlpatterns = [
    path('obivan/', admin.site.urls),
    path('send-msg/', SendFormTelegram.as_view(), name='send_message'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
    path('', include('pages.urls')),
    path('ordres/', include('orders.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

from pages.models import Colors


class Images(models.Model):
    images = models.ImageField(upload_to='products/%Y/%m/%d', default='static/no_image.png')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField('Категория', max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    in_home = models.BooleanField('На главную', default=False)
    position = models.IntegerField('Позиция', null=True, blank=True, default=0)
    description = models.CharField('краткое описание', max_length=200, db_index=True)
    image = models.ImageField(upload_to='category/%Y/%m/%d', default='static/no_image.png', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_by_category', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категрия'
        verbose_name_plural = 'Категрии'


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    tags = TaggableManager()
    attributes = models.ManyToManyField('Attributes', related_name='attributes')
    name = models.CharField('Название продукта', max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    description = models.TextField('Описание продукта', blank=True)
    price = models.IntegerField('Цена товара')
    sale = models.IntegerField('Скидка', default=0)
    hots = models.BooleanField('Новинки', default=False)
    in_home = models.BooleanField('На главную', default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.slug])

    def sale_percent(self):
        if self.sale > 0:
            percent = self.sale * self.price / 100
            return self.price - percent


class Attributes(models.Model):
    name = models.CharField('Название', max_length=255)
    detail = models.CharField('Характеристики', max_length=255)

    def __str__(self):
        return f'{self.name} - {self.detail}'

    class Meta:
        verbose_name = 'Характеристрика (Ширина)'
        verbose_name_plural = 'Характеристрики'

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='', min_value=1, widget=forms.NumberInput(attrs={'value': 1, 'class': 'cart-plus-minus-box'}))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    class Meta:
        fields = ['quantity', 'override']

templates/product/detail.html
{% extends 'base.html' %}
{% load static thumbnail %}
{% block title %}
{{ product.name|capfirst }} |
{% endblock %}
{% block content %}
    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row breadcrumb_box  align-items-center">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-center text-sm-start">
                            <h2 class="breadcrumb-title">{{ product.name|capfirst }}</h2>
                        </div>
                        <div class="col-lg-6  col-md-6 col-sm-6">
                            <!-- breadcrumb-list start -->
                            <ul class="breadcrumb-list text-center text-sm-end">
                                <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                                <li class="breadcrumb-item active">{{ product.name|capfirst }}</li>
                            </ul>
                            <!-- breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb-area end -->

    <div id="main-wrapper">
        <div class="site-wrapper-reveal">

            <div class="single-product-wrap section-space--pt_90 border-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7 col-md-6 col-sm-12 col-xs-12 mb-lg-3">
                            <!-- Product Details Left -->
                            <div class="product-details-left">
                                <div class="product-details-images-2 slider-lg-image-2">
                                    {% for image in product.images_set.all %}
                                        <div class="easyzoom-style">
                                            <div class="easyzoom easyzoom--overlay">
                                                {% thumbnail image.images "539x547" crop="center" as im %}
                                                    <a href="{{ im.url }}" class="poppu-img">
                                                        <img
                                                        src="{{ im.url }}"
                                                        class="img-fluid" alt="Product Images" width="{{ im.width }}"
                                                        height="{{ im.height }}">
                                                    </a>
                                                {% endthumbnail %}
                                            </div>
                                        </div>
                                    {% empty %}
                                        <a href="{% static 'no-image.png' %}" class="poppu-img">
                                            <img src="{% static 'no-image.png' %}" class="img-fluid" alt="{{ product.name}}"
                                            width="539x547">
                                        </a>
                                    {% endfor%}

                                </div>
                                <div class="product-details-thumbs-2 slider-thumbs-2">
                                    {% for image in product.images_set.all %}
                                        <div class="sm-image">
                                            {% thumbnail image.images "75x75" crop="center" as im %}
                                                <img
                                                src="{{ im.url }}"
                                                class="img-fluid" alt="Product Images" width="{{ im.width }}"
                                                height="{{ im.height }}">
                                            {% endthumbnail %}
                                        </div>
                                    {% endfor%}
                                </div>
                            </div>
                            <!--// Product Details Left -->


                        </div>
                        <div class="col-lg-5 col-md-6 col-sm-12 col-xs-12">
                            <div class="product-details-content ">

                                <h5 class="font-weight--reguler mb-10">{{ product.name|capfirst }}</h5>

                                {% if product.sale %}
                                    <div class="on-sale-price"><span class="new-price">{{ product.sale_percent }} ₽</span><span class="old-price">{{ product.price }} ₽</span> </div>
                                {% else %}
                                    <h3 class="price">{{ product.price }} ₽</h3>
                                {% endif %}

                                <div class="quickview-peragraph mt-10">
                                    <p>{{ product.description }}</p>
                                </div>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="quickview-action-wrap mt-30">

                                        <div class="quickview-cart-box">
                                            <div class="quickview-quality">
                                            </div>
                                            <div class="quickview-quality">
                                                <div class="cart-plus-minus">
                                                    <div class="dec qtybutton">-</div>
                                                    <input class="cart-plus-minus-box" id="id_quantity" type="text" name="quantity" value="1">
                                                    <div class="inc qtybutton">+</div></div>
                                            </div>

                                            <div class="quickview-button">
                                                <div class="quickview-cart button">
                                                    <input type="submit" value="В коризну"
                                                           class="btn--lg btn--black font-weight--reguler text-white">
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </form>

                                <div class="product_meta mt-30">
                                    {% for x in product.attributes.all %}
                                        <div class="sku_wrapper item_meta">
                                            <span class="label"> {{ x.name }}: </span> <span class="sku">{{ x.detail }}</span>
                                        </div>
                                    {% endfor %}
                                </div>

                                <div class="posted_in item_meta">
                                    <span class="label">Категория: </span><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/product/list.html
{% extends "base.html" %}
{% load static thumbnail %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Коллекция{% endif %}
{% endblock %}

{% block content %}
    <!-- breadcrumb-area start -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row breadcrumb_box  align-items-center">
                        <div class="col-lg-6 col-md-6 col-sm-6 text-center text-sm-start">
                            <h2 class="breadcrumb-title">
                                {% if category %}{{ category.name }}{% else %}Коллекция{% endif %}
                            </h2>
                        </div>
                        <div class="col-lg-6  col-md-6 col-sm-6">
                            <!-- breadcrumb-list start -->
                            <ul class="breadcrumb-list text-center text-sm-end">
                                <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                                <li class="breadcrumb-item active">
                                    {% if category %}{{ category.name }}{% else %}Коллекция{% endif %}</li>
                            </ul>
                            <!-- breadcrumb-list end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb-area end -->

    <div id="main-wrapper">
        <div class="site-wrapper-reveal border-bottom">
            <!-- Product Area Start -->
            <div class="product-wrapper section-space--ptb_60">
                <div class="container">

                    <div class="row">
                        <div class="col-lg-3 col-md-3 order-md-1 order-2  small-mt__40">
                            <div class="shop-widget widget-shop-categories">
                                <div class="product-filter">
                                    <h6 class="mb-20">Категории</h6>
                                    <ul class="widget-nav-list">
                                        <li {% if not category %}class="selected"{% endif %}>
                                            <a href="{% url "product_list" %}">Все</a>
                                        </li>
                                        {% for c in categories %}
                                            <li {% if category.slug == c.slug %}class="selected"
                                                {% endif %}>
                                                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <!-- Product Filter -->
                            <div class="shop-widget widget-size">
                                <div class="product-filter">
                                    <h6 class="mb-20">Назначение</h6>
                                    <ul class="widget-nav-list">
                                        {% for tag in tags %}
                                            <li class="{% if tag == current_tag %}actived{% endif %}"><a href="#">{{ tag.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-9 col-md-9  order-md-2 order-1">

                            <div class="row">
                                <div class="col-lg-6 col-md-8">
                                    <div class="shop-toolbar__items shop-toolbar__item--left">
                                        <div class="shop-toolbar__item shop-short-by">
                                            <ul>
                                                <li>
                                                    <a href="#">Сортировать: <span class="d-none d-sm-inline-block">По умолчанию</span>
                                                        <i class="fa fa-angle-down angle-down"></i></a>
                                                    <ul>
                                                        <li class="active"><a href="#">По цене: low to high</a></li>
                                                        <li><a href="#">По цене: high to low</a></li>
                                                    </ul>
                                                </li>

                                            </ul>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="tab_columns_01">
                                    <div class="row">
                                        {% for product in object_list %}
                                            <div class="col-lg-4 col-md-4 col-sm-6">
                                                <!-- Single Product Item Start -->
                                                <div class="single-product-item text-center">
                                                    <div class="products-images">
                                                        <a href="{{ product.get_absolute_url }}"
                                                           class="product-thumbnail">
                                                            {% if product.images_set.first %}
                                                                {% thumbnail product.images_set.first.images "269x269" crop="center" as im %}
                                                                    <img
                                                                    src="{{ im.url }}"
                                                                    class="img-fluid" alt="Product Images" width="{{ im.width }}"
                                                                    height="{{ im.height }}">
                                                                {% endthumbnail %}
                                                            {% else %}
                                                                <img src="{% static 'no-image.png' %}" class="img-fluid" alt="Product Images" width="300" height="300">
                                                            {% endif %}

                                                            {% if product.hots %}
                                                                <span class="ribbon out-of-stock">
                                                                HOTS
                                                            </span>
                                                            {% elif product.sale %}
                                                                <span class="ribbon onsale">
                                                                - {{ product.sale }}%
                                                            </span>
                                                            {% endif %}
                                                        </a>
                                                        <div class="product-actions">
                                                            <form action="{% url "cart:cart_add" product.id %}"
                                                                  method="post">
                                                                {% csrf_token %}
                                                                <p style="display: none">{{ cart_product_form }}</p>
                                                                <button style="border: none;"><i
                                                                        class="p-icon icon-bag2"></i> <span
                                                                        class="tool-tip">В коризну</span></button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                    <div class="product-content">
                                                        <h6 class="prodect-title"><a
                                                                href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                                        </h6>
                                                        <div class="prodect-price">
                                                            {% if product.sale_percent %}
                                                                <span class="new-price">{{ product.sale_percent }} ₽</span>
                                                                -
                                                                <strike class="old-price">{{ product.price }} ₽</strike>
                                                            {% else %}
                                                                <span class="old-price">{{ product.price }} ₽</span>
                                                            {% endif %}

                                                        </div>
                                                    </div>
                                                </div><!-- Single Product Item End -->
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-12">
                                        {% if is_paginated %}
                                            <ul class="page-pagination text-center mt-40">
                                                {% if page_obj.has_previous %}
                                                    <li><a class="next page-numbers"
                                                           href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                                                    </li>
                                                {% endif %}

                                                {% for i in paginator.page_range %}
                                                    {% if page_obj.number == i %}
                                                        <li>
                                                            <span class="page-numbers current">{{ i }}</span>
                                                        </li>
                                                    {% else %}
                                                        <li>
                                                            <a class="page-numbers" href="?page={{ i }}">{{ i }}</a>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}

                                                {% if page_obj.has_next %}
                                                    <li><a class="next page-numbers"
                                                           href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                                {% endif %}
                                            </ul>
                                        {% endif %}
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <!-- Product Area End -->
        </div>

    </div>
{% endblock %}