cart/urls.py
from django.urls import path
from cart.views import cart_add, cart_detail, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from orders.views import order_create

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
]

plyart_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import SendFormTelegram

urlpatterns = [
    path('obivan/', admin.site.urls),
    path('send-msg/', SendFormTelegram.as_view(), name='send_message'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
    path('', include('pages.urls')),
    path('ordres/', include('orders.urls')),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static thumbnail %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %} {% endblock %} {{ contacts.site_title_name }}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="icon" href="{% static 'assets/images/logo.png' %}">
    {% block meta %}

    {% endblock %}

    <!-- CSS
        ============================================ -->

    <link rel="stylesheet" href="{% static 'assets/css/vendor/vendor.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/plugins.min.css' %}">

    <!-- Main Style CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">


</head>

<body class="">

<!--====================  header area ====================-->
<div class="header-area header-area--default">

    <!-- Header Bottom Wrap Start -->
    <header class="header-area  header_height-120 header-sticky">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 col-md-4 d-none d-md-block">
                    <div class="header-left-search">
                        <div class="logo text-md-center">
                            <a href="{% url 'home' %}"><img src="{% static 'assets/images/logo.png' %}" alt=""
                                                            width="50%"></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-6"></div>
                <div class="col-lg-4 col-md-4 col-6">
                    <div class="header-right-side text-end">
                        <div class="header-right-items  d-none d-md-block">
                            <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" style="
                                border: 1px solid;
                                padding: 10px;
                                font-size: 12px;
                                border-radius: 5px;
                            ">Оставить заявку</i>
                            </a>
                        </div>

                        <div class="header-right-items">
                            <a href="#miniCart" class=" header-cart minicart-btn toolbar-btn header-icon"> <i
                                    class="icon-bag2"></i> <span class="item-counter">{{ cart|length }}</span> </a>
                        </div>
                        <div class="header-right-items">
                            <a href="#" class="mobile-navigation-icon" id="mobile-menu-trigger"> <i
                                    class="icon-menu"></i> </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Bottom Wrap End -->

</div>
<!--====================  End of header area  ====================-->

{% block content %}

{% endblock %}

<!--====================  footer area ====================-->
<div class="footer-area-wrapper">
    <div class="footer-area section-space--pt_40">
        <div class="container">
            <div class="row footer-widget-wrapper">
                <div class="col-lg-3 col-md-3 col-sm-6 footer-widget">
                    <h6 class="footer-widget__title mb-20">Контакты</h6>
                    <ul class="footer-widget__list">
                        <li><i class="icon_pin"></i> {{ contacts.address }}</li>
                        <li><i class="icon_phone"></i><a href="tel:{{ contacts.phone_number }}"
                                                         class="hover-style-link">{{ contacts.phone_number }}</a></li>
                        <li><i class="icon_mail"></i> <a href="mailto:{{ contacts.email }}" class="hover-style-link">{{ contacts.email }}</a></li>

                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 footer-widget">
                    <h6 class="footer-widget__title mb-20">Помощь и информация</h6>
                    <ul class="footer-widget__list">
                        {% for page in pages_list %}
                            <li><a target="_blank" href="{% url 'pages' page.slug %}"
                                   class="hover-style-link">{{ page.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 footer-widget">
                    <h6 class="footer-widget__title mb-20">О нас</h6>
                    <ul class="footer-widget__list">
                        <li><a href="{% url 'about' %}" class="hover-style-link">О нас</a></li>
                        <li><a href="{% url 'faq' %}" class="hover-style-link">FAQ</a></li>
                        <li><a href="{% url 'contacts' %}" class="hover-style-link">Контакты</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 footer-widget">
                    <h6 class="footer-widget__title mb-20">Рассылка</h6>
                    <div class="footer-widget__newsletter mt-30">
                        <form action="{% url 'send_message' %}" method="get" class="account-form-box">
                            <input type="text" placeholder="Ваш email">
                            <button class="submit-button"><i class="icon-arrow-right"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12">
            <span class="copyright-text text-center  section-space--mt_40">&copy; 2019 - {% now 'Y' %} Ply-Art.</span>
        </div>
    </div>
</div>
<!--====================  End of footer area  ====================-->


<!-- Modal -->
<div class="header-login-register-wrapper modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-box-wrapper">
                <div class="tab-content content-modal-box">
                    <div class="tab-pane fade show active" id="tab_list_06" role="tabpanel">
                        <form action="{% url 'send_message' %}" method="get" class="account-form-box">
                            {% csrf_token %}
                            <h6>Оставьте заявку</h6>
                            <div class="single-input">
                                <input type="text" name="name" placeholder="Имя">
                            </div>
                            <div class="single-input">
                                <input type="email" name="email" placeholder="Email">
                            </div>
                            <div class="single-input">
                                <input type="tel" name="phone" placeholder="Ваш телефон">
                            </div>
                            <div class="single-input">
                                <input type="text" name="message" placeholder="Комментарий">
                            </div>
                            <div class="button-box mt-25">
                                <button class="btn btn--full btn--black">Отправить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--====================  mobile menu overlay ====================-->
<div class="mobile-menu-overlay" id="mobile-menu-overlay">
    <div class="mobile-menu-overlay__inner">
        <div class="mobile-menu-close-box text-start">
            <span class="mobile-navigation-close-icon" id="mobile-menu-close-trigger"> <i
                    class="icon-cross2"></i></span>
        </div>
        <div class="mobile-menu-overlay__body">
            <nav class="offcanvas-navigation">
                <ul>
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'product_list' %}">Коллекция</a></li>
                    <li><a href="{% url 'faq' %}">FAQ</a></li>
                    <li><a href="{% url 'contacts' %}"><span>Контакты</span></a></li>
                </ul>
            </nav>

            <div class="mobile-menu-contact-info section-space--mt_60">
                <h6>Наши контакты</h6>
                <p>
                    {{ contacts.work_from|safe }}
                <hr>
                    <a href="tel:{{ contacts.phone_number }}" class="hover-style-link">{{ contacts.phone_number }}</a>
                <hr>
                    {{ contacts.address|safe }}
                </p>
            </div>

        </div>

    </div>

</div>
<!--====================  End of mobile menu overlay  ====================-->


<!--  offcanvas Minicart Start -->
<div class="offcanvas-minicart_wrapper" id="miniCart">
    <div class="offcanvas-menu-inner">
        <div class="close-btn-box">
            <a href="#" class="btn-close"><i class="icon-cross2"></i></a>
        </div>
        <div class="minicart-content">
            <ul class="minicart-list">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        {% for product in cart %}

                            <li class="minicart-product">
                                <a class="product-item_remove" href="{% url "cart:cart_remove" product.pk %}"><i
                                        class="icon-cross2"></i></a>
                                <a class="product-item_img" href="{% url "product_detail" product.slug %}">
                                    {% if product.image %}
                                            <img class="img-fluid" src="{{ product.image }}" alt="{{ product.name }}" width="75"
                                             height="75">
                                    {% else %}
                                        <img class="img-fluid" src="{% static 'no-image.png' %}" alt="{{ product.name }}" width="76"
                                         height="76">
                                    {% endif %}

                                </a>
                                <div class="product-item_content">
                                    <a class="product-item_title"
                                       href="{% url "product_detail" product.slug %}">{{ product.name }}</a> <label>Кол-во
                                    : <span>{{ product.quantity }}</span></label>

                                    <label class="product-item_quantity">Цена: <span> {{ product.price }}</span></label>
                                </div>
                            </li>

                        {% endfor %}
                    {% else %}
                        Ваша корзина пуста.
                    {% endif %}
                {% endwith %}
            </ul>
        </div>
        <div class="minicart-item_total">
            <span class="font-weight--reguler">Итого:</span> <span
                class="ammount font-weight--reguler">{{ cart.get_total_price }}</span>
        </div>
        <div class="minicart-btn_area">
            <a href="{% url 'cart:cart_detail' %}" class="btn btn--full btn--border_1">Корзина</a>
        </div>
        {% if cart|length > 0 %}
            <div class="minicart-btn_area">
                <a href="{% url 'orders:order_create' %}" class="btn btn--full btn--black">Купить</a>
            </div>
        {% endif %}
    </div>

    <div class="global-overlay"></div>
</div>
<!--  offcanvas Minicart End -->

<!--====================  scroll top ====================-->
<a href="#" class="scroll-top" id="scroll-top"> <i class="arrow-top icon-arrow-up"></i> <i
        class="arrow-bottom icon-arrow-up"></i> </a>
<!--====================  End of scroll top  ====================-->


<!-- JS
============================================ -->
<!-- Modernizer JS -->
<script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>

<!-- jQuery JS -->
<script src="{% static 'assets/js/vendor/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>

<!-- Bootstrap JS -->
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/plugins/plugins.js' %}"></script>


<!-- Main JS -->
<script src="{% static 'assets/js/main.js' %}"></script>


</body>

</html>